#Deeper Device Status

- platform: command_line
  name: "Deeper Status"
  command: "if curl --silent --max-time 3 --head --interface 'eth0' --request GET 'http://IPADDRESS' | grep 'HTTP/1.1 200 OK' > /dev/null; then echo 'Online'; else echo 'Offline';fi"
  scan_interval: 180
  unique_id: "DeeperStatus"
  command_timeout: 60

#Deeper Device Credit

- platform: command_line
  name: "Deeper Credit"
  command: "ssh root@homeassistant.local -p 22 -i /config/keys/SSH/HA-Private.pem -o StrictHostKeyChecking=no 'bash ./config/shell_scripts/deeper.sh credit IPADDRESS'"
  scan_interval: 180
  unique_id: "DeeperCredit"
  command_timeout: 60

#Deeper Device Balance

- platform: command_line
  name: "Deeper Balance"
  command: "ssh root@homeassistant.local -p 22 -i /config/keys/SSH/HA-Private.pem -o StrictHostKeyChecking=no 'bash ./config/shell_scripts/deeper.sh balance IPADDRESS'"
  scan_interval: 180
  unique_id: "DeeperBalance"
  command_timeout: 60

#Deeper Device Channel Balance

- platform: command_line
  name: "Deeper Channel Balance"
  command: "ssh root@homeassistant.local -p 22 -i /config/keys/SSH/HA-Private.pem -o StrictHostKeyChecking=no 'bash ./config/shell_scripts/deeper.sh channelBalance IPADDRESS'"
  scan_interval: 180
  unique_id: "DeeperChannelBalance"
  command_timeout: 60

#Deeper Device Consumed

- platform: command_line
  name: "Deeper Consumed"
  command: echo $(ssh root@homeassistant.local -p 22 -i /config/keys/SSH/HA-Private.pem -o StrictHostKeyChecking=no 'echo $(bash ./config/shell_scripts/deeper.sh consumed IPADDRESS)' | awk '{$1/=1024*2;printf "%.2fMB\n",$1}' | awk '{$1/=1024;printf "%.2fMB\n",$1}')
  scan_interval: 180
  unique_id: "DeeperConsumed"
  command_timeout: 60

#Deeper Device Shared

- platform: command_line
  name: "Deeper Shared"
  command: echo $(ssh root@homeassistant.local -p 22 -i /config/keys/SSH/HA-Private.pem -o StrictHostKeyChecking=no 'echo $(bash ./config/shell_scripts/deeper.sh shared IPADDRESS)' | awk '{$1/=1024*2;printf "%.2fMB\n",$1}' | awk '{$1/=1024;printf "%.2fMB\n",$1}')
  scan_interval: 180
  unique_id: "DeeperShared"
  command_timeout: 60

